doctrine:
    dbal:
        url: 'mysql://root:root@127.0.0.1:3308/checkmykicks?serverVersion=8.0.32&charset=utf8mb4'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App 