<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKWM3V74\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKWM3V74/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKWM3V74.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKWM3V74\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKWM3V74\App_KernelDevDebugContainer([
    'container.build_hash' => 'KWM3V74',
    'container.build_id' => '2706c9bf',
    'container.build_time' => 1749489559,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKWM3V74');
